- platform: iss
- platform: linode
  nodes:
    - 'linode2008320'
- platform: bayesian
  prior: 0.6
  name: 'Bayesian Presence Dan'
  probability_threshold: 0.82
  observations:
    - entity_id: 'device_tracker.dan2_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.dan_pixel2'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.dan2_owntracks'
      prob_given_true: 0.9
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
- platform: bayesian
  prior: 0.6
  name: 'Bayesian Presence Shelley'
  probability_threshold: 0.82
  observations:
    - entity_id: 'device_tracker.shelley_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.shelley_op3'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.shelley_owntracks'
      prob_given_true: 0.9
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
- platform: uptimerobot
  api_key: !secret uptimerobot_api_key

- platform: template
  sensors:
    home_power_status:
      friendly_name: 'Home Power Status'
      #delay_off:
      #  seconds: 90
      #device_class: power
      value_template: >-
          {%- if is_state("binary_sensor.home_power", "on") -%}
              True
          {%- elif is_state("binary_sensor.home_power", "off") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              True
          {%- endif -%}
    #   icon_template: >-
    #       {% if is_state("binary_sensor.home_power", "on") %}
    #          mdi:power-on
    #       {% elif is_state("binary_sensor.home_power", "off") %}
    #          mdi:power-off
    #       #This accounts for no state during startup until the sensor registers
    #       {% else %}
    #          mdi:power-on
    #       {% endif %}
      entity_id: binary_sensor.home_power
    camera_basement:
      friendly_name: 'Camera Basement'
      device_class: motion
      value_template: >-
          {%- if is_state("binary_sensor.blue_iris_basement", "on") -%}
              True
          {%- elif is_state("binary_sensor.blue_iris_basement", "off") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: binary_sensor.blue_iris_basement
    camera_backyard:
      friendly_name: 'Camera Backyard'
      device_class: motion
      value_template: >-
          {%- if is_state("binary_sensor.blue_iris_backyard", "on") -%}
              True
          {%- elif is_state("binary_sensor.blue_iris_backyard", "off") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: binary_sensor.blue_iris_backyard
    camera_craftroom:
      friendly_name: 'Camera Craft Room'
      device_class: motion
      value_template: >-
          {%- if is_state("binary_sensor.blue_iris_craftroom", "on") -%}
              True
          {%- elif is_state("binary_sensor.blue_iris_craftroom", "off") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: binary_sensor.blue_iris_craftroom
    camera_driveway:
      friendly_name: 'Camera Driveway'
      device_class: motion
      value_template: >-
          {%- if is_state("binary_sensor.blue_iris_driveway", "on") -%}
              True
          {%- elif is_state("binary_sensor.blue_iris_driveway", "off") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: binary_sensor.blue_iris_driveway
    camera_frontwalk:
      friendly_name: 'Camera Front Walk'
      device_class: motion
      value_template: >-
          {%- if is_state("binary_sensor.blue_iris_frontwalk", "on") -%}
              True
          {%- elif is_state("binary_sensor.blue_iris_frontwalk", "off") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: binary_sensor.blue_iris_frontwalk
    camera_garage:
      friendly_name: 'Camera Garage'
      device_class: motion
      value_template: >-
          {%- if is_state("binary_sensor.blue_iris_garage", "on") -%}
              True
          {%- elif is_state("binary_sensor.blue_iris_garage", "off") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: binary_sensor.blue_iris_garage
    camera_gatepatio:
      friendly_name: 'Camera Gate/Patio'
      device_class: motion
      value_template: >-
          {%- if is_state("binary_sensor.blue_iris_gatepatio", "on") -%}
              True
          {%- elif is_state("binary_sensor.blue_iris_gatepatio", "off") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: binary_sensor.blue_iris_gatepatio
    camera_livingroom:
      friendly_name: 'Camera Living Room'
      device_class: motion
      value_template: >-
          {%- if is_state("binary_sensor.blue_iris_livingroom", "on") -%}
              True
          {%- elif is_state("binary_sensor.blue_iris_livingroom", "off") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: binary_sensor.blue_iris_livingroom
    camera_patio:
      friendly_name: 'Camera Patio'
      device_class: motion
      value_template: >-
          {%- if is_state("binary_sensor.blue_iris_patio", "on") -%}
              True
          {%- elif is_state("binary_sensor.blue_iris_patio", "off") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: binary_sensor.blue_iris_patio

    den_ps3_status:
      friendly_name: 'Den PS3'
      value_template: >-
          {%- if is_state("device_tracker.den_ps3", "home") -%}
              True
          {%- elif is_state("device_tracker.den_ps3", "not_home") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: device_tracker.den_ps3
    den_ps4_status:
      friendly_name: 'Den PS4'
      value_template: >-
          {%- if is_state("device_tracker.den_ps4", "home") -%}
              True
          {%- elif is_state("device_tracker.den_ps4", "not_home") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: device_tracker.den_ps4
    den_amp_status:
      friendly_name: 'Den AMP'
      value_template: >-
          {%- if is_state("device_tracker.den_amp", "home") -%}
              True
          {%- elif is_state("device_tracker.den_amp", "not_home") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: device_tracker.den_amp
    den_lgtv_status:
      friendly_name: 'Den LG TV'
      value_template: >-
          {%- if is_state("device_tracker.den_lgtv", "home") -%}
              True
          {%- elif is_state("device_tracker.den_lgtv", "not_home") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: device_tracker.den_lgtv

    craft_motion:
      friendly_name: 'Craft Room Motion'
      device_class: motion
      value_template: >-
          {%- if is_state("sensor.craft_room_motion", "255") -%}
              True
          {%- elif is_state("sensor.craft_room_motion", "0") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              False
          {%- endif -%}
      entity_id: sensor.craft_room_motion

    connection_to_mysql:
      friendly_name: 'Connection to MySQL'
      value_template: >-
          {%- if is_state("sensor.connection_to_mysql", "True") -%}
              True
          {%- elif is_state("sensor.connection_to_mysql", "False") -%}
              False
          #This accounts for no state during startup until the sensor registers 
          {%- else -%}
              True
          {%- endif -%}
      entity_id: sensor.connection_to_mysql

    door_basement_test:
        friendly_name: 'Door Basement Test'
        device_class: door
        value_template: >-
            {%- if is_state("sensor.door_basement_raw", "255") -%}
                True
            {%- elif is_state("sensor.door_basement_raw", "0") -%}
                False
            #This accounts for no state during startup until the sensor registers
            {%- else -%}
                False
            {%- endif -%}
            entity_id: sensor.door_basement_raw