- platform: iss
- platform: linode
  nodes:
    - 'linode2008320'
- platform: bayesian
  prior: 0.6
  name: 'Bayesian Presence Dan'
  probability_threshold: 0.82
  observations:
    - entity_id: 'device_tracker.dan2_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.dan_pixel2'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.dan2_owntracks'
      prob_given_true: 0.9
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
- platform: bayesian
  prior: 0.6
  name: 'Bayesian Presence Shelley'
  probability_threshold: 0.82
  observations:
    - entity_id: 'device_tracker.shelley_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.shelley_op3'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.shelley_owntracks'
      prob_given_true: 0.9
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'