homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include_dir_merge_named customizations/

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest

# Enable config panel
config:

http:
#  api_password: !secret http_password
  base_url: !secret http_base_url
#  ssl_certificate: /etc/ssl/localcerts/fullchain.pem
#  ssl_key: /etc/ssl/localcerts/privkey.pem
  use_x_forwarded_for: True
  trusted_proxies:
    - 192.168.54.3
  ip_ban_enabled: true
  login_attempts_threshold: 10
#  trusted_networks:
#    - 192.168.9.0/24
#    - 10.242.2.0/24

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#Enable the map
map:

logger:
  default: warn

#Zwave Config
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config: !include zwave_device_config.yaml

#For the Amazon Echos
emulated_hue: !include emulated_hue.yaml

recorder: !include recorder.yaml

light:
  - platform: flux_led
    devices:
      192.168.9.216:
        name: den_tv_leds

hue:
  bridges:
    - host: 192.168.9.204

remote:
  - platform: harmony
    name: Den
    host: 192.168.9.208
    activity: Watch TV

# usps:
#  name: "USPS Home"
#  username: !secret usps_username
#  password: !secret usps_password
#  driver: chrome

#usps:
#    username: !secret usps_username
#    password: !secret usps_password

#Google Calendar integration
#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_client_secret

#IFTTT Integration
ifttt:
  key: !secret ifttt_key

#Alarm panel
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    armed_night:
      delay_time: 0
    armed_home:
      delay_time: 30
    armed_away:
      delay_time: 60

#MQTT discovery broker
#mqtt:
#  discovery: true
#  discovery_prefix: homeassistant

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

sense:
  email: !secret sense_email
  password: !secret sense_password
  timeout: 5

mqtt:
  broker: 192.168.9.56

linode:
  access_token: !secret linode_api_key

ecobee:
  api_key: !secret ecobee_api_key

wunderlist:
  client_id: !secret wunderlist_client_id
  access_token: !secret wunderlist_access_token

binary_sensor: !include binary_sensor.yaml

notify: !include notify.yaml

influxdb: !include influxdb.yaml

cover: !include cover.yaml

shell_command: !include shell_command.yaml

sensor: !include_dir_merge_list sensors

camera: !include cameras.yaml

device_tracker: !include device_tracker.yaml

switch: !include switch.yaml

media_player: !include media_player.yaml

group: !include groups.yaml

input_boolean: !include input_boolean.yaml

input_number: !include input_number.yaml

input_select: !include input_select.yaml

input_text: !include input_text.yaml

history_graph: !include history_graph.yaml

automation: !include_dir_merge_list automations

script: !include scripts.yaml

#scene: !include scenes.yaml

alexa:

intent_script: !include intent_script.yaml

zone: !include zone.yaml

water_heater: !include water_heater.yaml

#image_processing: !include image_processing.yaml
image_processing: !include_dir_merge_list tensorflow