homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enable config panel
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  ssl_certificate: /etc/ssl/localcerts/fullchain.pem
  ssl_key: /etc/ssl/localcerts/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 10
  trusted_networks:
    - 192.168.9.0/24
    - 10.242.2.0/24

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#For the Amazon Echos
emulated_hue:
  host_ip: 192.168.9.200
  type: alexa
  exposed_domains:
    - light
    - switch
#    - group
#    - media_player

recorder:
    purge_days: 3
    db_url: !secret recorder_db_url

#zwave:
#  usb_path: /dev/ttyACM0
#  polling_interval: 10000
#  device_config_domain:
#    light:
#      polling_intensity: 1
#      refresh_value: 2
#      delay: 3
#  device_config:
#    climate.main_thermostat_39:
#      polling_intensity: 1
#      refresh_value: 2
#      delay: 3
#    sensor.ac_energy_32_0:
#      polling_intensity: 1
#      refresh_value: 2
#      delay: 3
#    sensor.dryer_energy_33_0:
#      polling_intensity: 1
#      refresh_value: 2
#      delay: 3
#    sensor.furnace1_energy_34_0:
#      polling_intensity: 1
#      refresh_value: 2
#      delay: 3
#    sensor.furnace2_energy_35_0:
#      polling_intensity: 1
#      refresh_value: 2
#      delay: 3

light:
  platform: hue
  host: 192.168.9.204
  scan_interval: 30
  
notify:
  - name: danemail
    platform: smtp
    server: 192.168.9.1
    recipient: !secret dan_email
    sender: !secret email_from
  - name: shelleyemail
    platform: smtp
    server: 192.168.9.1
    recipient: !secret shelley_email
    sender: !secret email_from
  - name: dantext
    platform: smtp
    server: 192.168.9.1
    recipient: !secret dan_text
    sender: !secret email_from
  - name: shelleytext
    platform: smtp
    server: 192.168.9.1
    recipient: !secret shelley_text
    sender: !secret email_from
#  - name: push
#    platform: html5
#    gcm_api_key: !secret push_gcm_api_key
#    gcm_sender_id: !secret push_gcm_sender_id

#Google Calendar integration
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

#IFTTT Integration
ifttt:
  key: !secret ifttt_key

ffmpeg:
  ffmpeg_bin: /usr/bin/avconv

shell_command:
  #toggle_amp: curl "http://192.168.9.201:8081/msg?code=4B36D32C:NEC:32&pulse=2&pass=arduino"
  toggle_tv: curl -g 'http://192.168.9.201:8081/json?pass=arduino&plain=[{%22type%22:%22raw%22,%22data%22:[2450,600,%201250,600,%20700,600,%201250,600,%20700,600,%201250,600,%20700,600,%20700,600,%201250,600,%20700,600,%20700,600,%20700,600,%20700],%22khz%22:50,%22pulse%22:10}]'
  tplink_den_on: tplight on 192.168.9.199
  tplink_den_off: tplight off 192.168.9.199

#wink:
#  email: !secret wink_email
#  password: !secret wink_password
#  client_id: !secret wink_client_id
#  client_secret: !secret wink_client_secret

vera:
  vera_controller_url: http://192.168.9.205:3480/
#  lights: [22]

influxdb:
  host: 192.168.9.52
  database: hass
  whitelist:
    - sensor.ac_10
    - sensor.dryer_6
    - sensor.furnace1_13
    - sensor.furnace2_16
    - sensor.hot_water_heater_watts
    - sensor.server_rack_watts
    - sensor.home_26
    - sensor.pws_relative_humidity
    - sensor.pws_temp_f
    - sensor.climate_main_temperature2
    - sensor.main_thermostat_relative_humidity_31_5_3

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

sensor: !include sensors.yaml

binary_sensor:
  - platform: iss

camera dw:
  - platform: generic
    still_image_url: http://192.168.53.110/snap.jpeg
    name: Driveway

camera gp:
  - platform: generic
    still_image_url: http://192.168.53.112/snap.jpeg
    name: Back Gate/Patio

camera fw:
  - platform: generic
    still_image_url: http://192.168.53.111/snap.jpeg
    name: Front Walk

camera bs:
  - platform: generic
    still_image_url: http://192.168.53.113/snap.jpeg
    name: Backyard/Shed

camera cr:
  - platform: generic
    still_image_url: http://192.168.53.116/snap.jpeg
    name: Craft Room

camera bm:
  - platform: generic
    still_image_url: http://192.168.53.114/snap.jpeg
    name: Basement

camera lr:
  - platform: generic
    still_image_url: http://192.168.53.115/snap.jpeg
    name: Living Room

camera ga:
  - platform: generic
    still_image_url: http://192.168.53.117/snap.jpeg
    name: Garage

camera pa:
  - platform: generic
    still_image_url: http://192.168.53.118/snap.jpeg
    name: Patio

camera radar:
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=ILN&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=1.000&noclutter=1&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=0&smooth=1&rand=24788299&lat=0&lon=0&label=you
    name: Ohio Radar

device_tracker:
  - platform: ping
    hosts:
      shelley: 192.168.9.68
      dan: 192.168.9.69
      nick: 192.168.51.102
      shannon: 192.168.51.107

switch:
  - platform: wake_on_lan
    mac_address: "00-15-17-c7-c4-c4"
    name: VM1
    host: 192.168.9.26
  - platform: wake_on_lan
    mac_address: "00-1b-21-84-c4-ba"
    name: VM2
    host: 192.168.9.27

media_player:
  - platform: kodi
    host: 192.168.9.21
    name: Brix PC
    username: kodi
    password: kodi
    turn_off_action: quit
  - platform: onkyo
    host: 192.168.52.10
    name: Onkyo Den

group: !include groups.yaml

#input_select:
#  hvac_operation_mode:
#    name: 'Operating Mode'
#    options:
#      - 'Auto'
#      - 'Cool'
#      - 'Heat'
#      - 'Aux Heat'
#      - 'Off'
#    initial: Cool
#    icon: mdi:settings
#  hvac_fan_mode:
#    name: 'Fan Mode'
#    options:
#      - 'Auto'
#      - 'On'
#    initial: Auto
#    icon: mdi:fan

input_slider:
  random_hour:
    name: 'Random Hour'
    min: 0
    max: 23
    step: 1
    initial: 22
  random_minute:
    name: 'Random Minute'
    min: 0
    max: 59
    step: 1
    initial: 45
  dr_off_delay:
    name: 'DR Off Delay'
    min: 0
    max: 20
    step: .5
    initial: 1

automation:  !include automations.yaml

script: !include scripts.yaml

scene: !include scenes.yaml

alexa:
  intents:
    ActivateSceneIntent:
      action:
        service: scene.turn_on
        data_template:
          entity_id: scene.{{ Scene | replace(" ", "_") }}
      speech:
        type: plaintext
        text: !include alexa_confirm.yaml
    RunScriptIntent:
      action:
        service: script.turn_on
        data_template:
          entity_id: script.{{ Script | replace(" ", "_") }}
      speech:
        type: plaintext
        text: !include alexa_confirm.yaml


zone:
  name: Dan Work
  latitude: !secret dan_work_lat
  longitude: !secret dan_work_lon
  radius: 200
