homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customizations.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
#    green:
#      primary-color: green

# Enable config panel
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  ssl_certificate: /etc/ssl/localcerts/fullchain.pem
  ssl_key: /etc/ssl/localcerts/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 10
  trusted_networks:
    - 192.168.9.0/24
    - 10.242.2.0/24

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#Enable the map
map:

#Start the embeded broker
#mqtt:

#Enable the statestream for data flow between devices
#mqtt_statestream:
#  base_topic: homeassistant
#  publish_attributes: true
#  publish_timestamps: true

#logger:
#  logs:
#    pyHS100: debug
#    homeassistant.components.light.tplink: debug

#Zwave Config
zwave:
  usb_path: /dev/ttyACM0

#For the Amazon Echos
emulated_hue:
  host_ip: 192.168.9.200
#  type: alexa
  exposed_domains:
    - light
    - switch
#    - group
#    - media_player

#Required values are to be piped to InfluxDB
#Only keep the minimum needed in MySQL for quick reference.
recorder:
    purge_interval: 1
    purge_keep_days: 7
    db_url: !secret recorder_db_url

#Connect to the Hue hub
light:
  - platform: hue
    host: 192.168.9.204
    scan_interval: 30
#  - platform: tplink
#    host: 192.168.9.199
#    name: Den

usps:
    username: !secret usps_username
    password: !secret usps_password

#Google Calendar integration
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

#IFTTT Integration
ifttt:
  key: !secret ifttt_key

#Vera integration
vera:
  vera_controller_url: http://192.168.9.205:3480/

binary_sensor:
  - platform: iss

notify: !include notify.yaml

influxdb: !include influxdb.yaml

cover: !include cover.yaml

shell_command: !include shell_command.yaml

#sensor: !include sensors.yaml
sensor: !include_dir_merge_list sensors

camera: !include cameras.yaml

device_tracker: !include device_tracker.yaml

switch: !include switch.yaml

media_player: !include media_player.yaml

group: !include groups.yaml

input_boolean: !include input_boolean.yaml

input_number: !include input_number.yaml

history_graph: !include history_graph.yaml

#automation: !include automations.yaml
automation: !include_dir_merge_list automations

script: !include scripts.yaml

scene: !include scenes.yaml

alexa:

intent_script: !include intent_script.yaml

zone: !include zone.yaml

