- platform: ping
  consider_home: 600
  hosts:
    shelley_ping: 192.168.55.152
    dan_ping: 192.168.9.69
    dan2_ping: 192.168.55.153
#    nick: 192.168.51.101
#    shannon: 192.168.51.107
- platform: owntracks_http
- platform: unifi
  username: !secret unifi_user
  password: !secret unifi_pass
  host: 192.168.9.47
  port: 8443
  site_id: ihj7qv3c
  verify_ssl: false