- platform: ping
  consider_home: 600
  hosts:
    shelley_ping: 192.168.55.152
    dan_ping: 192.168.9.69
    dan2_ping: 192.168.55.153
#    ps3: 192.168.52.12
#    ps4: 192.168.52.11
#    lgtv: 192.168.9.65
#    nick: 192.168.51.101
#    shannon: 192.168.51.107
- platform: ping
  consider_home: 30
  hosts:
    den_amp: 192.168.52.10
    den_ps3: 192.168.52.12
    den_ps4: 192.168.52.11
    den_lgtv: 192.168.9.65
    kids_tv: 192.168.51.108
    kids_xbox: 192.168.51.105
#- platform: owntracks_http
- platform: gpslogger
- platform: unifi
  username: !secret unifi_user
  password: !secret unifi_pass
  host: 192.168.9.47
  port: 8443
  site_id: ihj7qv3c
  verify_ssl: false