- platform: kodi
  host: 192.168.9.21
  name: Brix PC
  username: !secret kodi_user
  password: !secret kodi_pass
  enable_websocket: false
  turn_off_action:
    service: media_player.kodi_call_method
    data:
      entity_id: media_player.brix_pc
      method: Application.Quit
- platform: onkyo
  host: 192.168.52.10
  name: Onkyo Den
  #sources:
  #  video6: 'PC'
  #  cd: 'Record'
- platform: alexa
  email: !secret amazon_email
  password: !secret amazon_password
  url: amazon.com