- name: danemail
  platform: smtp
  server: 192.168.9.1
  recipient: !secret dan_email
  sender: !secret email_from
- name: shelleyemail
  platform: smtp
  server: 192.168.9.1
  recipient: !secret shelley_email
  sender: !secret email_from
- name: dantext
  platform: smtp
  server: 192.168.9.1
  recipient: !secret dan_text
  sender: !secret email_from
- name: shelleytext
  platform: smtp
  server: 192.168.9.1
  recipient: !secret shelley_text
  sender: !secret email_from
- name: shannontext
  platform: smtp
  server: 192.168.9.1
  recipient: !secret shannon_text
  sender: !secret email_from
- name: nicktext
  platform: smtp
  server: 192.168.9.1
  recipient: !secret nick_text
  sender: !secret email_from
- name: push
  platform: html5
  vapid_pub_key: !secret push_cloud_messaging_pub_key
  vapid_prv_key: !secret push_cloud_messaging_prv_key
  vapid_email: !secret push_cloud_messaging_email
- name: slacknotify
  platform: slack
  api_key: !secret slack_api_key
  default_channel: '#ha'
- platform: kodi
  name: kodinotify
  host: 192.168.9.21
  username: !secret kodi_user
  password: !secret kodi_pass
- name: danpushover
  platform: pushover
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key
- name: ecobee
  platform: ecobee