- platform: command_line
  name: "XRP to USD"
  command: 'python3 /scripts/kraken_ripple.py'
  unit_of_measurement: "USD"
- platform: command_line
  name: "ETH to USD"
  command: 'python3 /scripts/kraken_eth.py'
  unit_of_measurement: "USD"
- platform: command_line
  name: "Speedtest Download"
  command: '/scripts/parse_speedtest.sh download'
  unit_of_measurement: "Mbit/s"
- platform: command_line
  name: "Speedtest Upload"
  command: '/scripts/parse_speedtest.sh upload'
  unit_of_measurement: "Mbit/s"
- platform: command_line
  name: "Speedtest Ping"
  command: '/scripts/parse_speedtest.sh latency'
  unit_of_measurement: "ms"
- platform: command_line
  name: "Database Size"
  command: '/bin/bash -c /scripts/get_db_size.sh'
  unit_of_measurement: "GB"
- platform: command_line
  name: "InfluxDB Size"
  command: '/bin/bash -c /scripts/get_influxdb_size.sh'
  unit_of_measurement: "MB"
- platform: command_line
  name: "BTC to USD"
  command: 'python3 /scripts/coinbase_btc.py'
  unit_of_measurement: "USD"
- platform: command_line
  name: "Kids WiFi Status"
  command: 'php /scripts/ubnt/check_network.php Dev_Kids false'
- platform: command_line
  name: "/r/homeautomation Subsribers"
  command: 'php /scripts/hasub_sub.php'
- platform: command_line
  name: "IO Latency"
  command: '/scripts/disk_io.sh'
- platform: command_line
  name: snmp_sophos_wan_traffic
  command: snmpget -v 2c -c public -Oqv 192.168.9.1 1.3.6.1.2.1.2.2.1.10.3 1.3.6.1.2.1.2.2.1.16.3 | tr '\n' '|'
  scan_interval: 10