#Storage NAS
- platform: qnap
  host: 192.168.9.6
  username: !secret qnap_storage_user
  password: !secret qnap_storage_pass
  verify_ssl: false
  monitored_conditions:
    - status
    - system_temp
    - cpu_temp
    - cpu_usage
    - memory_free
    - memory_used
    - memory_percent_used
    - network_link_status
    - network_tx
    - network_rx
    - drive_smart_status
    - drive_temp
    - volume_size_free
    - volume_size_used
    - volume_percentage_used

#iSCSI NAS:
- platform: qnap
  host: 192.168.9.24
  username: !secret qnap_iscsi_user
  password: !secret qnap_iscsi_pass
  verify_ssl: false
  monitored_conditions:
    - status
    - system_temp
    - cpu_temp
    - cpu_usage
    - memory_free
    - memory_used
    - memory_percent_used
    - network_link_status
    - network_tx
    - network_rx
    - drive_smart_status
    - drive_temp
    - volume_size_free
    - volume_size_used
    - volume_percentage_used