- alias: 'flash_front_start'
  trigger:
    platform: state
    entity_id: input_boolean.halloween_show
    to: 'on'
  action:
    service: script.turn_on
    entity_id: script.flash_front

- alias: 'flash_front_stop'
  trigger:
    platform: state
    entity_id: input_boolean.halloween_show
    to: 'off'
  action:
    service: script.turn_off
    entity_id: script.flash_front