- id: set_theme_on_startup
  alias: 'Set theme at startup'
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: darkred

- id: update_notifications
  alias: Update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.danemail
    data:
      title: 'New Home Assistant Release'
      message: "Home Assistant  {{ states.updater.updater.state }}  is now available."

- id: chest_freezer_left_open
  alias: Chest Freezer Left Open
  trigger:
    platform: state
    entity_id: sensor.chest_freezer_state
    from: 'Closed'
    to: 'Open'
    for:
       minutes: 3
  action:
    - service: notify.dantext
      data:
        message: 'CHEST FREEZER LEFT OPEN!'
    - service: notify.danemail
      data:
        message: 'CHEST FREEZER LEFT OPEN!'

- alias: Monitor Traffic
  trigger:
    platform: state
    entity_id: sensor.snmp_wan_in
  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.internet_traffic_delta_in
        value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'

- alias: Monitor Traffic
  trigger:
    platform: state
    entity_id: sensor.snmp_wan_out
  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.internet_traffic_delta_out
        value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'

- alias: Notify When Dan Leaving Work
  trigger:
    platform: zone
    entity_id: device_tracker.dan_owntracks
    zone: zone.dan_work
    event: leave
  condition:
    condition: time
    after: '16:00:00'
    before: '18:00:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: notify.dantext
    data_template:
      message: >
        Dan is {{ states.sensor.dan_location_to_home.state_with_unit }} from home!

- alias: Notify When Shelley Leaving Work
  trigger:
    platform: zone
    entity_id: device_tracker.shelley_owntracks
    zone: zone.shelley_work
    event: leave
  condition:
    condition: time
    after: '07:00:00'
    before: '08:00:00'
  action:
    service: notify.dantext
    data_template:
      message: >
        Shelley is {{ states.sensor.shelley_location_to_home.state_with_unit }} from home!